// Generated by CoffeeScript 1.8.0
(function() {
  this.BookmarkItem = (function() {
    function BookmarkItem(bookmark) {
      this.bookmark = bookmark;
      this.bookmarkId = this.bookmark.id;
    }

    BookmarkItem.prototype.render = function($viewport) {
      var $label, $link;
      this.$viewport = $viewport;
      this.$el = document.createElement("li");
      this.$el.className = "bookmark-item";
      if (!this.bookmark.url) {
        this.$el.className += " folder-item";
      }
      $link = document.createElement("a");
      $label = document.createElement("span");
      $link.className = "clearfix";
      if (!this.isFolder()) {
        $link.setAttribute("href", this.bookmark.url);
      }
      $link.addEventListener("mouseover", (function(_this) {
        return function() {
          if (_this.mouseoutTimeout) {
            clearTimeout(_this.mouseoutTimeout);
            return _this.mouseoutTimeout = null;
          } else {
            return _.delay(function() {
              var _ref;
              return (_ref = _this.delegate) != null ? typeof _ref.BookmarkItemDidMouseOver === "function" ? _ref.BookmarkItemDidMouseOver(_this) : void 0 : void 0;
            }, 110);
          }
        };
      })(this), false);
      $link.addEventListener("mouseout", (function(_this) {
        return function() {
          if (!_this.mouseoutTimeout) {
            return _this.mouseoutTimeout = _.delay(function() {
              var _ref;
              if ((_ref = _this.delegate) != null) {
                if (typeof _ref.BookmarkItemDidMouseOut === "function") {
                  _ref.BookmarkItemDidMouseOut(_this);
                }
              }
              return _this.mouseoutTimeout = null;
            }, 100);
          }
        };
      })(this), false);
      $link.addEventListener("mousedown", (function(_this) {
        return function() {
          var _ref;
          return (_ref = _this.delegate) != null ? typeof _ref.BookmarkItemWillClick === "function" ? _ref.BookmarkItemWillClick(_this) : void 0 : void 0;
        };
      })(this), false);
      $link.addEventListener("click", (function(_this) {
        return function() {
          var _ref;
          return (_ref = _this.delegate) != null ? typeof _ref.BookmarkItemDidClick === "function" ? _ref.BookmarkItemDidClick(_this) : void 0 : void 0;
        };
      })(this), false);
      $label.innerHTML = this.bookmark.title.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
      if (this.isFolder()) {
        $label.innerHTML += " &raquo;";
      }
      $link.appendChild($label);
      this.$el.appendChild($link);
      this.$link = $link;
      return this.$viewport.appendChild(this.$el);
    };

    BookmarkItem.prototype.isFolder = function() {
      return !this.bookmark.url;
    };

    return BookmarkItem;

  })();

}).call(this);
