// Generated by CoffeeScript 1.8.0
(function() {
  this.BookmarksBar = (function() {
    function BookmarksBar() {
      this.bookmarksLoaded = new RSVP.Promise((function(_this) {
        return function(resolve, reject) {
          return chrome.bookmarks.getChildren("1", function(bookmarks) {
            _this.bookmarks = bookmarks;
            return resolve(_this.bookmarks);
          });
        };
      })(this));
    }

    BookmarksBar.prototype.render = function($viewport) {
      this.$viewport = $viewport;
      this.$el = document.createElement("div");
      this.$el.id = "bookmarks-bar";
      this.$viewport.appendChild(this.$el);
      return this.bookmarksLoaded.then((function(_this) {
        return function() {
          _this.mainBookmarksList = new BookmarksList(_this.bookmarks, {
            delegate: _this
          });
          _this.mainBookmarksList.render(_this.$el);
          _this.otherBookmarksList = new BookmarksList([
            {
              id: "2",
              title: "Other Bookmarks"
            }
          ], {
            delegate: _this
          });
          _this.otherBookmarksList.render(_this.$el);
          return _this.otherBookmarksList.$el.className += " other-bookmarks";
        };
      })(this));
    };

    BookmarksBar.prototype.hidePopupIfPresent = function() {
      this.otherBookmarksList.hidePopupIfPresent();
      return this.mainBookmarksList.hidePopupIfPresent();
    };

    BookmarksBar.prototype.BookmarksListDidOpenFolder = function(bookmarksList) {
      if (bookmarksList === this.mainBookmarksList) {
        return this.otherBookmarksList.hidePopupIfPresent();
      } else {
        return this.mainBookmarksList.hidePopupIfPresent();
      }
    };

    BookmarksBar.prototype.BookmarksListDidMouseOverItem = function(bookmarksList, bookmarkItem) {
      if (bookmarkItem.isFolder()) {
        if (bookmarksList === this.mainBookmarksList) {
          return this.otherBookmarksList.hidePopupIfPresent();
        } else {
          return this.mainBookmarksList.hidePopupIfPresent();
        }
      } else {
        return this.hidePopupIfPresent();
      }
    };

    return BookmarksBar;

  })();

}).call(this);
